### ISSUE TITLE
5 Script typos + 1 typo

### ISSUE THREAD

**Issue by TotoR115** [Gitjas/Ascalons_Breagar#1]
there are several object in script file that have no reference ingame.

`acbre_bg2_ar0603.baf: `
in the block:

> IF
> 	Global("ACBre_DestroyAxeID","MYAREA",0)
> 	PartyHasItem("c#br0003")
> THEN
> 	RESPONSE #100
>         ActionOverride("Container3",DestroyItem("ACAXE"))
>         ActionOverride("Container3",DestroyItem("ACAXE2"))
>         ActionOverride("Container3",DestroyItem("ACAXE3"))
> 		SetGlobal("ACBre_DestroyAxeID","MYAREA",1)
> END

c#br0003 does not exist. it could be something like :

> 	OR(3)
> 	  PartyHasItem("ACAXE")
> 	  PartyHasItem("ACAXE2")
> 	  PartyHasItem("ACAXE3")

`actrig01.baf:`
in the block:

> IF
> 	IsOverMe([PC])
> 	InMyArea("ACBRE")
> 	Global("ACBRESET","LOCALS",0)
> 	OpenState("DOOR08",TRUE)
> THEN
> 	RESPONSE #100
> 		SetGlobal("ACBRESET","LOCALS",1)
> 		ActionOverride("ACBRE",ChangeAIScript("ACBREBG2",OVERRIDE)
> END

ACBREBG2.bcs does not exist. could be ACBRE.bcs

`ACCUT15X.BAF:`
ACFORCUT.bcs does not exist

`ACCUT15Y.BAF:`
ACFORCUT.bcs does not exist

`ACCUT15Z.BAF:`
ACFORCUT.bcs does not exist

there is 1 typo in `game-ACBRE.tra` line 444:
1s12+6 instead of 1d12+6

**Comment by Gitjas** [comment]
Thank you! ACFORCUT.bcs does not exist indeed, the other instances will be fixed in v12.0.0.
