### ISSUE TITLE
Tiny Typo #1

### ISSUE THREAD

**Issue by TotoR115** [Gitjas/Ascalons_Breagar#2]
There are 2 typos:
https://github.com/Gitjas/Ascalons_Breagar/blob/344077a1470e00fef37fc2acb5872f1998b91480/ACBre/d/both/ACAsc.D#L35
Should be `Montaron `instead of `Monatron`

https://github.com/Gitjas/Ascalons_Breagar/blob/344077a1470e00fef37fc2acb5872f1998b91480/ACBre/d/both/ACAsc.D#L44
Should be `Garrick`instead of `Garrik`

**Comment by Gitjas** [comment]
Thanks! (I really don't seem to like these names.)
